/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.lbenda.coursing.client.gui;

import cz.lbenda.coursing.client.ClientServiceLocator;
import cz.lbenda.coursing.dto.Breed;
import cz.lbenda.coursing.service.BreedService;
import java.awt.BorderLayout;
import java.beans.Customizer;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/**
 *
 * @author Lukas Benda <lbenda at lbenda.cz>
 */
public class BreedForm extends javax.swing.JPanel implements Customizer {

  private DTOPanel dtoPanel;

  /**
   * Creates new form BreedForm
   */
  public BreedForm() {
    initComponents();
    initComponentsDTO();
  }

  private void initComponentsDTO() {
    pDTO.setLayout(new BorderLayout());
    dtoPanel = new DTOPanel();
    pDTO.add(dtoPanel, BorderLayout.CENTER);
  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pDTO = new javax.swing.JPanel();
    lName = new javax.swing.JLabel();
    tfName = new javax.swing.JTextField();
    lComment = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    taComment = new javax.swing.JTextArea();

    pDTO.setMaximumSize(new java.awt.Dimension(32767, 60));
    pDTO.setMinimumSize(new java.awt.Dimension(100, 60));
    pDTO.setPreferredSize(new java.awt.Dimension(0, 60));

    javax.swing.GroupLayout pDTOLayout = new javax.swing.GroupLayout(pDTO);
    pDTO.setLayout(pDTOLayout);
    pDTOLayout.setHorizontalGroup(
      pDTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    pDTOLayout.setVerticalGroup(
      pDTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 86, Short.MAX_VALUE)
    );

    org.openide.awt.Mnemonics.setLocalizedText(lName, org.openide.util.NbBundle.getMessage(BreedForm.class, "BreedForm.lName.text")); // NOI18N

    tfName.setText(org.openide.util.NbBundle.getMessage(BreedForm.class, "BreedForm.tfName.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(lComment, org.openide.util.NbBundle.getMessage(BreedForm.class, "BreedForm.lComment.text")); // NOI18N

    taComment.setColumns(20);
    taComment.setRows(5);
    jScrollPane1.setViewportView(taComment);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pDTO, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lName)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfName))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lComment)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lName)
          .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lComment)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pDTO, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lComment;
  private javax.swing.JLabel lName;
  private javax.swing.JPanel pDTO;
  private javax.swing.JTextArea taComment;
  private javax.swing.JTextField tfName;
  // End of variables declaration//GEN-END:variables

  private Breed breed;

  @Override
  public void setObject(Object bean) {
    setBreed((Breed) bean);
  }

  public void setBreed(Breed breed) {
    this.breed = breed;
    tfName.setText(breed.getName());
    taComment.setText(breed.getComment());
    this.dtoPanel.setDTO(breed);
  }

  public Breed getBreed() {
    breed.setName(tfName.getText());
    breed.setComment(taComment.getText());
    return breed;
  }

  public static void showDialog(Breed breed) {
    final BreedForm form = new BreedForm();
    form.setBreed(breed);
    NotifyDescriptor nd = new NotifyDescriptor.Confirmation(form, Bundle.CTL_ChangePasswordForm(),
            NotifyDescriptor.OK_CANCEL_OPTION);
    if (NotifyDescriptor.OK_OPTION.equals(DialogDisplayer.getDefault().notify(nd))) {
      BreedService bs = (BreedService) ClientServiceLocator.getInstance().getBean(BreedService.class);
      bs.save(form.getBreed());
    }
  }
}
