/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.lbenda.coursing.client.gui;

import javax.swing.DefaultListModel;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/**
 *
 * @author Lukas Benda <lbenda at lbenda.cz>
 */
public class ChooseDialog<T extends Object> extends javax.swing.JPanel {

  private final T[] options;

  /**
   * Creates new form ChooseDialog
   */
  public ChooseDialog(T[] options) {
    initComponents();
    this.options = options;
    DefaultListModel dlm = new DefaultListModel();
    for (T o : options) { dlm.addElement(o); }
    lChoose.setModel(dlm);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    lChoose = new javax.swing.JList();

    jScrollPane1.setViewportView(lChoose);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList lChoose;
  // End of variables declaration//GEN-END:variables

  public T getSelectedOption() {
    return (T) this.lChoose.getSelectedValue();
  }

  public static <T extends Object> T showDialog(String title, T[] options) {
    final ChooseDialog<T> form = new ChooseDialog<>(options);
    NotifyDescriptor nd = new NotifyDescriptor.Confirmation(form, title, NotifyDescriptor.OK_CANCEL_OPTION);
    if (NotifyDescriptor.OK_OPTION.equals(DialogDisplayer.getDefault().notify(nd))) {
      return form.getSelectedOption();
    }
    return null;
  }
}
