/*
 * Copyright 2014 Lukas Benda <lbenda at lbenda.cz>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cz.lbenda.coursing.client.gui;

import cz.lbenda.common.IntegerHelper;
import cz.lbenda.coursing.client.ClientServiceLocator;
import cz.lbenda.coursing.dto.DogPlacement;
import cz.lbenda.coursing.service.DogPlacementService;
import java.awt.BorderLayout;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/**
 *
 * @author Lukas Benda <lbenda at lbenda.cz>
 */
public class DogPlacementForm extends javax.swing.JPanel {

  private DTOPanel dtoPanel;
  private final DogPlacement dogPlacement;

  /** Creates new form DogPlacementForm */
  public DogPlacementForm(DogPlacement dogPlacement) {
    initComponents();
    initComponentsDTO();
    this.dogPlacement = dogPlacement;

    tfBreed.setText(IntegerHelper.integerToString(dogPlacement.getPlacementBreed()));
    tfGender.setText(IntegerHelper.integerToString(dogPlacement.getPlacementGender()));
    tfGenderBreed.setText(IntegerHelper.integerToString(dogPlacement.getPlacementGenderBreed()));
    tfTotal.setText(IntegerHelper.integerToString(dogPlacement.getPlacementTotal()));
  }

  private void initComponentsDTO() {
    pDTO.setLayout(new BorderLayout());
    dtoPanel = new DTOPanel();
    pDTO.add(dtoPanel, BorderLayout.CENTER);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pDTO = new javax.swing.JPanel();
    lBreed = new javax.swing.JLabel();
    lGender = new javax.swing.JLabel();
    lGenderBreed = new javax.swing.JLabel();
    lTotal = new javax.swing.JLabel();
    tfBreed = new javax.swing.JTextField();
    tfGender = new javax.swing.JTextField();
    tfGenderBreed = new javax.swing.JTextField();
    tfTotal = new javax.swing.JTextField();

    pDTO.setMaximumSize(new java.awt.Dimension(32767, 60));
    pDTO.setMinimumSize(new java.awt.Dimension(100, 60));
    pDTO.setPreferredSize(new java.awt.Dimension(0, 60));

    javax.swing.GroupLayout pDTOLayout = new javax.swing.GroupLayout(pDTO);
    pDTO.setLayout(pDTOLayout);
    pDTOLayout.setHorizontalGroup(
      pDTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    pDTOLayout.setVerticalGroup(
      pDTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 60, Short.MAX_VALUE)
    );

    org.openide.awt.Mnemonics.setLocalizedText(lBreed, org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.lBreed.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(lGender, org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.lGender.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(lGenderBreed, org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.lGenderBreed.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(lTotal, org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.lTotal.text")); // NOI18N

    tfBreed.setText(org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.tfBreed.text")); // NOI18N

    tfGender.setText(org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.tfGender.text")); // NOI18N

    tfGenderBreed.setText(org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.tfGenderBreed.text")); // NOI18N

    tfTotal.setText(org.openide.util.NbBundle.getMessage(DogPlacementForm.class, "DogPlacementForm.tfTotal.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pDTO, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lGenderBreed)
          .addComponent(lTotal)
          .addComponent(lGender)
          .addComponent(lBreed))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tfBreed)
          .addComponent(tfGender)
          .addComponent(tfTotal)
          .addComponent(tfGenderBreed))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pDTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lBreed)
          .addComponent(tfBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lGender)
          .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lGenderBreed)
          .addComponent(tfGenderBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lTotal)
          .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 10, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lBreed;
  private javax.swing.JLabel lGender;
  private javax.swing.JLabel lGenderBreed;
  private javax.swing.JLabel lTotal;
  private javax.swing.JPanel pDTO;
  private javax.swing.JTextField tfBreed;
  private javax.swing.JTextField tfGender;
  private javax.swing.JTextField tfGenderBreed;
  private javax.swing.JTextField tfTotal;
  // End of variables declaration//GEN-END:variables

  public DogPlacement getDogPlacement() {
    dogPlacement.setPlacementBreed(IntegerHelper.stringToInteger(tfBreed.getText()));
    dogPlacement.setPlacementGender(IntegerHelper.stringToInteger(tfGender.getText()));
    dogPlacement.setPlacementGenderBreed(IntegerHelper.stringToInteger(tfGenderBreed.getText()));
    dogPlacement.setPlacementTotal(IntegerHelper.stringToInteger(tfTotal.getText()));
    return dogPlacement;
  }

  public static void showDialog(DogPlacement dogPlacement) {
    final DogPlacementForm form = new DogPlacementForm(dogPlacement);
    NotifyDescriptor nd = new NotifyDescriptor.Confirmation(form, Bundle.DLG_LapForm_Save(),
            NotifyDescriptor.OK_CANCEL_OPTION);
    if (NotifyDescriptor.OK_OPTION.equals(DialogDisplayer.getDefault().notify(nd))) {
      DogPlacement dp = form.getDogPlacement();
      DogPlacementService dps = ClientServiceLocator.getInstance().getBean(DogPlacementService.class);
      dps.save(dp);
    }
  }
}
