/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.lbenda.coursing.client.gui;

import cz.lbenda.coursing.client.ClientServiceLocator;
import cz.lbenda.coursing.client.gui.action.BreedAddCookie;
import cz.lbenda.coursing.client.gui.action.BreedDelCookie;
import cz.lbenda.coursing.dto.Breed;
import cz.lbenda.coursing.service.AbstractDTOService;
import cz.lbenda.coursing.service.BreedService;
import java.awt.BorderLayout;
import java.beans.IntrospectionException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Action;
import javax.swing.JTable;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.swing.outline.DefaultOutlineCellRenderer;
import org.openide.actions.PropertiesAction;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.BeanNode;
import org.openide.nodes.ChildFactory;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.actions.SystemAction;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//cz.lbenda.coursing.client.gui//FrmBreed//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "FrmBreedTopComponent",
        iconBase = "cz/lbenda/coursing/client/icon/breed.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "cz.lbenda.coursing.client.gui.FrmBreedTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FrmBreedAction",
        preferredID = "FrmBreedTopComponent"
)
@Messages({
  "CTL_FrmBreedAction=Breed",
  "CTL_FrmBreedTopComponent=Breed",
  "HINT_FrmBreedTopComponent=List of all breeds"
})
public final class FrmBreedTopComponent extends TopComponent implements ExplorerManager.Provider {

  private static final Logger LOG = LoggerFactory.getLogger(FrmBreedTopComponent.class);
  private final ExplorerManager em = new ExplorerManager();
  private final OutlineView ov;
  private final InstanceContent ic = new InstanceContent();
  private BreedChildFactory breedChildrenFactory;
  private AbstractDTOService.DTOChangedListener<Breed> DTOChangedListener;

  public FrmBreedTopComponent() {
    initComponents();
    setName(Bundle.CTL_FrmBreedTopComponent());
    setToolTipText(Bundle.HINT_FrmBreedTopComponent());

    setLayout(new BorderLayout());
    ov = new OutlineView();
    ov.getOutline().setRootVisible(false);
    ov.getOutline().setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    ColumnCellRenderer ccr = new ColumnCellRenderer();

    ccr.setCentered(false);
    // ov.getOutline().setDefaultRenderer(Node.Property.class, ccr);
    ov.getOutline().setDefaultRenderer(Node.Property.class, new DefaultOutlineCellRenderer());
    add(ov, BorderLayout.CENTER);
    breedChildrenFactory = new BreedChildFactory();
    Node rootNode = new AbstractNode(Children.create(breedChildrenFactory, true));
    em.setRootContext(rootNode);
    definePropertyAndHint();

    ic.add(breedAddCookie);
    ic.add(em);
    ic.add(getActionMap());
    associateLookup(new AbstractLookup(ic));
  }

  private void definePropertyAndHint() {
    ov.setPropertyColumns("name", "Name", "comment", "Comment"); // FIXME - localization
    // TODO description of column
  }

  private BreedAddCookie breedAddCookie = new BreedAddCookie() {};

  @Override
  public ExplorerManager getExplorerManager() {
    return em;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  @Override
  public void componentOpened() {
    // TODO add custom code on component opening
  }

  @Override
  public void componentClosed() {
    // TODO add custom code on component closing
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  void readProperties(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }

  public static class BreedNode extends BeanNode<Breed> {
    public BreedNode(final Breed breed) throws IntrospectionException {
      this(breed, new InstanceContent());
    }
    public BreedNode(final Breed breed, final InstanceContent ic) throws IntrospectionException {
      super(breed, Children.LEAF, new AbstractLookup(ic));
      ic.add(new BreedDelCookie() { public @Override Breed removedBreed() { return breed; } } );
    }
    @Override
    public Action getPreferredAction() {
      return SystemAction.get(PropertiesAction.class);
    }
    @Override
    public Action[] getActions(boolean context) {
      List<? extends Action> actions = Utilities.actionsForPath("Actions/Coursing/Breed");
      Action[] result = new Action[actions.size() + 1];
      result[0] = SystemAction.get(PropertiesAction.class);
      for (int i = 0; i < actions.size(); i++) { result[i + 1] = actions.get(i); }
      return result;
    }
  }

  public class BreedChildFactory extends ChildFactory<Breed> implements AbstractDTOService.DTOChangedListener<Breed> {
    private final BreedService breedService = ClientServiceLocator.getInstance().getBean(BreedService.class);
    private final List<Breed> newBreeds = new ArrayList<>();
    public BreedChildFactory() {
    }
    public final void close() {
      breedService.removeDTOChangedListener(this);
      newBreeds.clear();
    }
    public final void open() {
      breedService.addDTOChangedListener(this);
    }
    @Override
    protected  boolean createKeys(List<Breed> toPopulate) {
      LOG.debug("createKeys");
      if (toPopulate.isEmpty()) { toPopulate.addAll(breedService.allEntities()); } // Adding completely new data
      for (Breed breed : newBreeds) {
        if (!toPopulate.contains(breed)) { toPopulate.add(breed); }
      }
      return true;
    }
    @Override
    protected Node createNodeForKey(Breed key) {
      try {
        return new BreedNode(key);
      } catch (IntrospectionException ex) {
        LOG.error("Faild the creating node of DTO", ex);
      }
      return null;
    }
    @Override
    public void dtoChanged(Breed oldDTO, Breed newDTO) {
      LOG.debug("oldDTO, newDTO");
      if (oldDTO == null && !newBreeds.contains(newDTO)) {
        LOG.debug("refresh");
        newBreeds.add(newDTO);
        refresh(true);
      }
    }
  }
}
