/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.lbenda.coursing.client.gui;

import cz.lbenda.common.IntegerHelper;
import cz.lbenda.coursing.dto.NumberLine;
import cz.lbenda.coursing.service.AbstractDTOService;
import java.awt.BorderLayout;
import java.beans.Customizer;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/** Form for editing number line
 * @author Lukas Benda <lbenda at lbenda.cz>
 */
public class NumberLineForm extends javax.swing.JPanel implements Customizer {

  private DTOPanel dtoPanel;

  /**
   * Creates new form NumberLineForm
   */
  public NumberLineForm() {
    initComponents();
    initComponentsDTO();
  }

  private void initComponentsDTO() {
    pDTO.setLayout(new BorderLayout());
    dtoPanel = new DTOPanel();
    pDTO.add(dtoPanel, BorderLayout.CENTER);
  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pDTO = new javax.swing.JPanel();
    lName = new javax.swing.JLabel();
    tfName = new javax.swing.JTextField();
    lComment = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    taComment = new javax.swing.JTextArea();
    lSort = new javax.swing.JLabel();
    tfSort = new javax.swing.JTextField();

    pDTO.setMaximumSize(new java.awt.Dimension(32767, 60));
    pDTO.setMinimumSize(new java.awt.Dimension(100, 60));
    pDTO.setPreferredSize(new java.awt.Dimension(0, 60));

    javax.swing.GroupLayout pDTOLayout = new javax.swing.GroupLayout(pDTO);
    pDTO.setLayout(pDTOLayout);
    pDTOLayout.setHorizontalGroup(
      pDTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    pDTOLayout.setVerticalGroup(
      pDTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 86, Short.MAX_VALUE)
    );

    org.openide.awt.Mnemonics.setLocalizedText(lName, org.openide.util.NbBundle.getMessage(NumberLineForm.class, "NumberLineForm.lName.text")); // NOI18N

    tfName.setText(org.openide.util.NbBundle.getMessage(NumberLineForm.class, "NumberLineForm.tfName.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(lComment, org.openide.util.NbBundle.getMessage(NumberLineForm.class, "NumberLineForm.lComment.text")); // NOI18N

    taComment.setColumns(20);
    taComment.setRows(5);
    jScrollPane1.setViewportView(taComment);

    org.openide.awt.Mnemonics.setLocalizedText(lSort, org.openide.util.NbBundle.getMessage(NumberLineForm.class, "NumberLineForm.lSort.text")); // NOI18N

    tfSort.setText(org.openide.util.NbBundle.getMessage(NumberLineForm.class, "NumberLineForm.tfSort.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
      .addComponent(pDTO, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(lComment)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lName)
          .addComponent(lSort))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tfName)
          .addComponent(tfSort)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(pDTO, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lName)
          .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lSort)
          .addComponent(tfSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lComment)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lComment;
  private javax.swing.JLabel lName;
  private javax.swing.JLabel lSort;
  private javax.swing.JPanel pDTO;
  private javax.swing.JTextArea taComment;
  private javax.swing.JTextField tfName;
  private javax.swing.JTextField tfSort;
  // End of variables declaration//GEN-END:variables

  private NumberLine numberLine;

  @Override
  public void setObject(Object bean) {
    setNumberLine((NumberLine) bean);
  }

  public void setNumberLine(NumberLine numberLine) {
    this.numberLine = numberLine;
    tfName.setText(numberLine.getName());
    taComment.setText(numberLine.getComment());
    tfSort.setText(IntegerHelper.integerToString(numberLine.getSort()));
    this.dtoPanel.setDTO(numberLine);
  }

  public NumberLine getNumberLine() {
    numberLine.setName(tfName.getText());
    numberLine.setComment(taComment.getText());
    numberLine.setSort(IntegerHelper.stringToInteger(tfSort.getText()));
    return numberLine;
  }

  public static void showDialog(NumberLine numberLine, AbstractDTOService<NumberLine> numberLineService) {
    final NumberLineForm form = new NumberLineForm();
    form.setNumberLine(numberLine);
    NotifyDescriptor nd = new NotifyDescriptor.Confirmation(form, Bundle.CTL_ChangePasswordForm(),
            NotifyDescriptor.OK_CANCEL_OPTION);
    if (NotifyDescriptor.OK_OPTION.equals(DialogDisplayer.getDefault().notify(nd))) {
      numberLineService.save(form.getNumberLine());
    }
  }
}
